sudo: false
osx_image: xcode7
language: objective-c
cache:
  directories:
    - node_modules
    - .nvm
before_install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 4
  - npm install -g npm@2
  - npm install
  - npm install -g react-native-cli
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run codecov
