sudo: false
osx_image: xcode8
language: objective-c
cache:
  edge: true
  bundler: true
  cocoapods: true
  directories:
    - .nvm
    - node_modules
    - vendor/bundle
before_install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
install:
  - nvm install stable
  - yarn global add react-native-cli
  - yarn
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - bundle install --path=vendor/bundle
before_script:
  - npm prune
script:
  - npm test
after_success:
  - "[ -f coverage/lcov.info ] && npm run codecov || echo 'coverage file not found'"
