sudo: false
osx_image: xcode7
language: objective-c
cache:
  directories:
    - .nvm
    - node_modules
    - vendor/bundle
before_install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
install:
  - nvm install 5
  - npm install -g npm
  - npm install -g react-native-cli
  - npm install
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - bundle install --path=vendor/bundle
before_script:
  - npm prune
script:
  - npm test
after_success:
  - "[ -f coverage/lcov.info ] && npm run codecov || echo 'coverage file not found'"
